name: Dependency Updates

on:
  schedule:
    # Run at 2 AM UTC every Monday
    - cron: '0 2 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'  # TODO: change back to 'yarn' when git dependency is fixed

      - name: Install dependencies
        run: npm ci  # TODO: change back to 'yarn install --frozen-lockfile' when git dependency is fixed

      - name: Update dependencies
        run: |
          # Update non-breaking changes  
          npm update

      - name: Test build after updates
        run: |
          npm run build
          if [ ! -f "main.js" ]; then
            echo "Build failed - main.js not created"
            exit 1
          fi

      - name: Run tests
        run: npm run test
        continue-on-error: true  # Don't fail on test issues

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet package-lock.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            Automated dependency update

            This PR updates dependencies to their latest compatible versions.
            
            **Changes:**
            - Updated package-lock.json with latest compatible versions
            - Verified build still works
            - Tests run (may have some failures due to external dependencies)
            
            Please review the changes before merging.
          branch: chore/update-dependencies
          delete-branch: true